baseURL = '//pardonmynoot.com/'
languageCode = 'en'
title = 'Pardon my Noot'
theme = "gokarna"

author = "Peritz"
copyright = "Peritz (https://github.com/peritz), all rights reserved"

pluralizelisttitles = false
paginate = 10
enableEmoji = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 20

    [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/index.xml"
        weight = 30
    
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 40
    
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 50

[params]
    author = "Peritz"
    description = "Security penguin and privacy nut. Ready your tinfoil hats and let's go on an adventure."
    avatarURL = "/images/peritz-face.png"
    accentColor = "#703ACB"
    togglePreviousAndNextButtons = "true"
    showPostsOnHomePage = "recent"
    footer = "Peritz (https://github.com/peritz), all rights reserved"
    socialIcons = [
        {name = "github", url = "https://github.com/peritz"},
        {name = "email", url = "mailto:peritz@pardonmynoot.com"}
    ]
    [params.style]
        darkestColor = "#1f1f1f"
        darkColor = "#2a2a2a"
        lightColor = "#bbbbbb"
        lightestColor = "#d0d0d0"
        primaryColor = "#703acb"


